"""Initial migration.

Revision ID: ac4e3a5ebc5a
Revises: 
Create Date: 2024-08-28 00:18:31.992787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4e3a5ebc5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board', sa.String(length=9), nullable=False),
    sa.Column('current_player', sa.String(length=1), nullable=False),
    sa.Column('winner', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
